config/routes.rb
Rails.application.routes.draw do
    root to: "pages#index"
    get 'animations', to: 'pages#animations'
    get 'stories', to: 'projects#stories'
    resources :sites
    resources :contacts, only: [:new, :create]
    resources :projects
    devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
    attribute :name,        :validate => true
    attribute :email,       :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
    attribute :message,     :validate => true
    attribute :nickname,    :captcha  => true

    # Declare the e-mail headers. It accepts anything the mail method
    # in ActionMailer accepts.
    def headers
        {
            :subject => "My Contact Form",
            :to => "hello@gjrevans.com",
            :from => %("#{name}" <#{email}>)
        }
    end
end

app/models/project.rb
class Project < ApplicationRecord
    extend FriendlyId
    friendly_id :title, use: :slugged
    enum status: { unpublished: 0, preview: 1, published: 2 }
end

app/models/site.rb
class Site < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def create
        ContactMailer.contact_confirmation(Contact.new(params[:contact])).deliver
        flash[:info] = "Thanks, your message was sent!"
        redirect_to root_path
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
        @contact = Contact.new
        @projects = Project.where(status: :published).order('id ASC')
        @sites = Site.all
        @technologies = JSON.parse(File.read('public/json/technologies.json'))
    end
    def animations
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :authenticate_user!, except: [:show, :stories]
    before_action :set_project, only: [:show, :edit, :update, :destroy]

    def index
        @projects = Project.order('id ASC')
    end

    def stories
        @projects = Project.order('id ASC')
    end

    def show
        if @project.unpublished?
            flash[:danger] = "Oh no, that project is unpublushed!"
            redirect_to root_path
        end
        @projects = Project.where(status: :published).order("RANDOM()").limit(3)

        @word_count = @project.description.scan(/\w+/).size
    end


    def new
        @project = Project.new
    end

    def edit
    end

    def create
        @project = Project.new(project_params)
        if @project.save
            flash[:success] = 'Project was successfully created!'
            redirect_to @project
        else
            render :new
        end
    end

    def update
        if @project.update(project_params)
            flash[:success] = 'Project was successfully updated!'
            redirect_to @project
        else
            render :edit
        end
    end

    def destroy
        @project.destroy
        flash[:success] = 'Project was successfully deleted!'
        redirect_to projects_url
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
        @project = Project.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
        params.require(:project).permit(:title, :image, :banner, :date, :description, :summary, :link, :status)
    end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
    before_action :authenticate_user!, except: [:show]
    before_action :set_site, only: [:show, :edit, :update, :destroy]

    # GET /sites
    # GET /sites.json
    def index
        @sites = Site.all
    end

    # GET /sites/1
    # GET /sites/1.json
    def show
    end

    # GET /sites/new
    def new
        @site = Site.new
    end

    # GET /sites/1/edit
    def edit
    end

    # POST /sites
    def create
        @site = Site.new(site_params)
        if @site.save
            redirect_to @site, notice: 'Site was successfully created.'
        else
            render :new
        end
    end

    # PATCH/PUT /sites/1
    def update
        if @site.update(site_params)
            redirect_to @site, notice: 'Site was successfully updated.'
        else
            render :edit
        end
    end

    # DELETE /sites/1
    def destroy
        @site.destroy
        redirect_to sites_url, notice: 'Site was successfully destroyed.'
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
        @site = Site.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
        params.require(:site).permit(:title, :image, :github, :link, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def notify_class_for(flash_type)
    { success: "success", error: "danger", alert: "warning", notice: "info" }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/contacts/_contact.html.erb
<h5 class="section--title">Contact</h5>
<p>Let's get in touch, network, or whatever else it is you do via a contact form.</p>
<%= form_for @contact do |f| %>
<div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", placeholder: "John Doughboy", required: true %>
</div>
    <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: "form-control", placeholder: "doughboy@booblybob.com", required: true %>
    </div>
    <div class="form-group">
        <%= f.label :message %>
        <%= f.text_area :message, class: "form-control", placeholder: "Let's build something cool together!", required: true %>
    </div>
    <div class="form-group hidden">
        <%= f.label :nickname %>
        <%= f.text_area :nickname, hint: "leave this field blank" %>
    </div>
    <%= f.button "Send Message", class: "btn btn-primary btn-full-width", data: {disable_with: "<i class='fa fa-spinner fa-pulse'></i> Submitting Message"} %>
<% end %>

app/views/contacts/_project_cards.html.erb
<% @projects.each do |project| %>
<div class="col-md-4">
    <div class="card">
        <%= image_tag project.image, class:"card-img-top", alt:"codego" %>
        <div class="card-block">
            <h4 class="card-title"><%= project.title %></h4>
            <p class="small"><%= project.date %></p>
            <p class="card-text"><%= project.summary %></p>
            <%= link_to "Read the Story", project_path(project), class: "btn btn-block btn-primary" %>
            <% if user_signed_in? %>
                <%= link_to 'Edit', edit_project_path(project), class: "btn btn-block btn-primary" %>
            <% end %>
        </div>
    </div>
</div>
<% end %>

app/views/contacts/new.html.erb
<section id="welcome">
    <!-- IMAGE BACKGROUND -->
    <div id="welcomeImage"></div>
    <!-- HEADER BEGIN -->
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2 class="title">Hi, I'm Gordon</h2>
                <div class="subtitle">
                    <p>I'm a seasoned product guy who builds startups for a living.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section id="about" class="section--white text-xs-center">
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <h5 class="section--title">About</h5>
                <p>There are two main reasons for this site's existence.</p>
                <p>First, I've wanted to create up a personal site for a quite awhile now, so <code>hello world</code>. Second, I'd like to use this site as the boilerplate for a bunch of frontend experimentation.</p>
                <p>So, that's why the site's here, but you may also be wondering who I am.<p>
                <p>While its potentially unhealthy, I feel that the answer to that question is probably best answered with what I do for a living. Currently, I'm employed at a place called <a href="#work">Wirkn</a> where I head up the product & engineering team.</p>
                <p>When I started school nearly 10 years ago excited about a future in mechanical engineering, I never imagined that someday I'd leave it behind to instead create software from my couch.</p>
                <p>But, thanks to handful of meaningful co-op expieriences at <a href="https://uwaterloo.ca">UW</a>, some seriously hard work and a bit of dumb luck I've found success in the product end of the startup world and have massively enjoyed breathing life into new products for the better part of the last decade.</p>
            </div>
        </div>
    </div>
</section>
<section id="work" class="section--grey text-xs-center">
    <div class="container">
        <div class="row text-xs-center">
            <div class="col-md-12">
                <h5 class="section--title mb-1">Stories n'Stuff</h5>
                <p class="mb-3">A collection of my favourite projects, a few rants and some longer stories.</p>
            </div>
            <%= render partial: "project_cards" %>
        </div>
    </div>
</section>

<!-- CONTACT FORM -->
<%= render partial: "contact" %>

app/views/layouts/_footer.html.erb
<section class="bg-primary py-12">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-4">
        <!-- SOCIAL LINKS -->
        <ul class="d-flex w-100 align-items-center justify-content-between list-unstyled mb-0">
          <li>
            <%= link_to "https://www.twitter.com/gjrevans", target: "_blank", class: "text-white" do %>
              <span class="fa fa-twitter fa-2x"></span>
            <% end %>
          </li>
          <li>
            <%= link_to "https://www.facebook.com/gjrevans", target: "_blank", class: "text-white" do %>
              <span class="fa fa-facebook fa-2x"></span>
            <% end %>
          </li>
          <li>
            <%= link_to "https://www.instagram.com/gjrevans", target: "_blank", class: "text-white" do %>
              <span class="fa fa-instagram fa-2x"></span>
            <% end %>
          </li>
          <li>
            <%= link_to "https://www.youtube.com/user/gj2393", target: "_blank", class: "text-white" do %>
              <span class="fa fa-youtube-play fa-2x"></span>
            <% end %>
          </li>
          <li>
            <%= link_to "https://www.linkedin.com/in/gjrevans", target: "_blank", class: "text-white" do %>
              <span class="fa fa-linkedin fa-2x"></span>
            <% end %>
          </li>
          <% if user_signed_in? %>
            <li>
              <%= link_to destroy_user_session_path, method: :delete, class: "text-white" do %>
                <span class="fa fa-sign-out fa-2x"></span>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to new_user_session_path, class: "text-white" do %>
                <span class="fa fa-sign-in fa-2x"></span>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_header.html.erb
<nav class="nav--top nav--root js-navigation">
    <div class="container">
        <div class="row flex-items-sm-middle">
            <div class="col-4">
                <div class="nav--avatar--wrapper">
                    <%= link_to image_tag("avatar.jpg"), "/#welcome", class: "nav--avatar" %>
                </div>
            </div>
            <div class="col-8">
                <ul class="nav--list">
                    <li class="nav--link"><%= link_to "About", "/#about" %></li>
                    <li class="nav--link"><%= link_to "Stories", "/#stories" %></li>
                    <li class="nav--link"><%= link_to "Contact", "/#contact" %></li>
                </ul>
            </div>
        </div>
    </div>
</nav>

app/views/layouts/_mars_landing.html.erb
<div class="space">
    <div class="ship">
        <div class="ship-rotate">
            <div class="pod"></div>
            <div class="fuselage"></div>
        </div>
    </div>
    <div class="ship-shadow"></div>
    <div class="mars">
        <div class="tentacle"></div>
        <div class="flag">
            <div class="small-tentacle"></div>
        </div>
        <div class="planet">
            <div class="surface"></div>
            <div class="crater1"></div>
            <div class="crater2"></div>
            <div class="crater3"></div>
        </div>
    </div>
    <div class="test"></div>
</div>

app/views/layouts/_notify.html.erb
<script type="text/javascript">
	<% flash.each do |type, message| %>
		$.notify({
			// options
			message: "<%= sanitize(message) %>"
		},{
			// settings
			offset: 10,
			delay: 5000,
			type: "<%= notify_class_for(type) %>"
		});
	<% end %>
</script>

app/views/layouts/_technologies.html.erb
<% @technologies.each do |technology| %>
<div class="col-md-2 col-sm-4 col-6 text-center">
    <%= image_tag technology['image'], class:"img-fluid rounded", alt: technology['name'] %>
    <h6 class="mt-3"><%= link_to technology['name'], technology['link'], target: '_blank' %></h6>
    <p class="small"><%= technology['info'] %></p>
</div>
<% end %>

app/views/pages/animations.html.erb
<div class="orb-container">
    <div class="orb"></div>
    <div class="orb"></div>
    <div class="orb"></div>
    <div class="orb"></div>
    <div class="orb"></div>
    <div class="orb"></div>
    <div class="orb"></div>
</div>

<div class="ship">
    <div class="ship-rotate">
        <div class="pod"></div>
        <div class="fuselage"></div>
    </div>
</div>

app/views/projects/_project_card.html.erb
<% @projects.each do |project| %>
<div class="col-md-4">
    <div class="card">
        <%= image_tag project.image, class:"card-img-top", alt:"codego" %>
        <div class="card-block">
            <h4 class="card-title"><%= project.title %></h4>
            <p class="small"><%= project.date %></p>
            <p class="card-text"><%= project.summary %></p>
            <%= link_to "Read Story", project_path(project), class: "btn btn-block btn-primary" %>
            <% if user_signed_in? %>
                <%= link_to 'Edit', edit_project_path(project), class: "btn btn-block btn-primary" %>
            <% end %>
        </div>
    </div>
</div>
<% end %>

app/views/projects/_project_cards.html.erb
<% @projects.each do |project| %>
<div class="col-md-4">
    <div class="card">
        <%= image_tag project.image, class:"card-img-top", alt:"codego" %>
        <div class="card-block">
            <h4 class="card-title"><%= project.title %></h4>
            <p class="small"><%= project.date %></p>
            <p class="card-text"><%= project.summary %></p>
            <%= link_to "Read Story", project_path(project), class: "btn btn-block btn-primary" %>
            <% if user_signed_in? %>
                <%= link_to 'Edit', edit_project_path(project), class: "btn btn-block btn-primary" %>
            <% end %>
        </div>
    </div>
</div>
<% end %>

app/views/projects/edit.html.erb
<div id="pageContent" class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Editing Project</h1>

            <%= render 'form', project: @project %>
            <div class="float-sm-left">
                <%= link_to 'Show', @project, class: "btn btn-primary" %>
                <%= link_to 'Back', projects_path, class: "btn btn-primary" %>
            </div>
        </div>
    </div>
</div>

app/views/projects/index.html.erb
<div id="pageContent" class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="float-sm-left">Projects</h1>
            <div class="float-sm-right">
                <%= link_to 'New Project', new_project_path, class: "btn btn-primary" %>
            </div>
            <table class="table table-hover">
                <thead class="thead-inverse">
                    <tr>
                        <th>#</th>
                        <th>Title</th>
                        <th>Image</th>
                        <th>Date</th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                </thead>

                <tbody>
                    <% @projects.each do |project| %>
                    <tr>
                        <th scope="row"><%= project.id %></th>
                        <td><%= project.title %></td>
                        <td><a tabindex="0" role="button" data-toggle="popover" data-trigger="focus" title="Project Image" data-content='<img src="<%= image_url(project.image) %>" style="width:100%;height:170px;" alt="Project Image">'>Image</a></td>
                        <td><%= project.date %></td>
                        <td><%= project.status %></td>
                        <td>
                            <%= link_to project, title: "show" do %><span class="fa fa-eye mr-1"></span><% end %>
                            <%= link_to edit_project_path(project), title: "edit" do %><span class="fa fa-edit mr-1"></span><% end %>
                            <%= link_to project, method: :delete, data: { confirm: 'Are you sure?' }, title: "delete" do %><span class="fa fa-times"></span><% end %>
                        </td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script type="text/javascript">
$(function () {
    $('[data-toggle="popover"]').popover({
        placement : 'right',
        trigger : 'hover',
        html : true
    });
})
</script>

app/views/projects/new.html.erb
<div id="pageContent" class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>New Project</h1>

            <%= render 'form', project: @project %>
            <div class="float-sm-left">
                <%= link_to 'Back', projects_path, class: "btn btn-primary" %>
            </div>
        </div>
    </div>
</div>

app/views/projects/show.html.erb
<div id="projectImage" style="background: url(<%= @project.banner %>)"></div>
<div id="pageContent" class="container">
    <div class="row">
        <div class="col-md-12">
            <nav class="breadcrumb pt-0">
                <%= link_to "Home", root_path, class: "breadcrumb-item" %>
                <% if user_signed_in? %>
                <%= link_to "Projects", projects_path, class: "breadcrumb-item" %>
                <% end %>
                <%= link_to @project.title, "#", class: "breadcrumb-item active" %>
            </nav>
            <div class="read-time-floater animated bounceInRight box-shadow">
                <div class="read-time-content">
                    <div class="read-time-number" id="timeLeft"></div>
                    <div class="small">MINUTES</div>
                </div>
            </div>
            <div class="row flex-items-sm-middle">
                <div class="col-md-6">
                    <h2><%= @project.title %></h2>
                    <p class="font-weight-bold small"><%= @project.date %></p>
                </div>
                <div class="col-md-6 text-sm-right">
                    <% if @project.link.present? %>
                    <%= link_to "Visit #{@project.title}", @project.link, class: "btn btn-primary", target: "_blank" %>
                    <% end %>
                </div>
            </div>

            <div id="projectDescription" class="py-3">
                <p><%= simple_format(@project.description) %></p>
            </div>
            <hr>
            <!-- RANDOM PROJECTS -->
            <h5 id="endOfProject">Some Other Projects</h5>
            <div class="row pt-2">
                <%= render partial: "projects/project_card" %>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        // Add Responsive Class
        $("#projectDescription img").addClass("img-fluid");

        // Basic Word Count
        var $wordsPerMinute = 150;
        $("#timeLeft").html((<%= @word_count %> / $wordsPerMinute).toFixed(2));

        // Calulate Read Time on load, scroll & resize
        $(window).scroll(function (event) {
            calculateReadTime();
        });

        function calculateReadTime() {
            // Constants
            var $topOffest = $("#projectDescription").offset().top;
            var $lineHeight = 34;

            // Window Width
            var $windowWidth = $(window).width();

            // Words per line based on screen width (!very arbitrary cunt!)
            if ( $windowWidth > 1200) {
                var $wordPerLine =  21;
            } else if ( $windowWidth > 991) {
                var $wordPerLine =  17;
            } else if ( $windowWidth > 768) {
                var $wordPerLine =  14;
            } else if ( $windowWidth > 500) {
                var $wordPerLine =  10;
            } else {
                var $wordPerLine =  7;
            }

            // Calculate time left based on scroll postion
            var $scroll = $(window).scrollTop();
            var $distanceToEnd = $("#endOfProject").offset().top - $scroll;
            var $timeLeft = (((($distanceToEnd - $topOffest) / $lineHeight) * $wordPerLine) / $wordsPerMinute).toFixed(2);

            // Put updated time into the floater
            $("#timeLeft").html($timeLeft);

            // Fade out when you reach the bottom
            if ($timeLeft < 0.1) {
                $(".read-time-floater").fadeOut(200);
            } else {
                $(".read-time-floater").fadeIn(200);
            }
        };
    });
</script>

app/views/projects/stories.html.erb
<section id="stories" class="section--grey text-sm-center">
  <div class="container">
    <div class="row text-sm-center">
      <div class="col-md-12">
        <h5 class="section--title mb-2">Stories</h5>
        <p>Slowly growing a collection of my startup stores, rants, etc.</p>
      </div>
      <%= render partial: "projects/project_card" %>
    </div>
  </div>
</section>

app/views/sites/_form.html.erb
<%= form_for(site) do |f| %>
<% if site.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(site.errors.count, "error") %> prohibited this site from being saved:</h2>

    <ul>
        <% site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="from-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
</div>

<div class="from-group">
    <%= f.label :image %>
    <%= f.text_field :image, class: 'form-control' %>
</div>

<div class="from-group">
    <%= f.label :github %>
    <%= f.text_field :github, class: 'form-control' %>
</div>

<div class="from-group">
    <%= f.label :link %>
    <%= f.text_field :link, class: 'form-control' %>
</div>

<div class="from-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
</div>

<div class="row mt-3">
    <div class="col-md-6">
        <div class="from-group">
            <%= f.submit 'Submit', class: 'btn btn-primary form-control' %>
        </div>
    </div>
    <div class="col-md-6">
        <%= link_to 'Back', sites_path, class: 'btn btn-primary form-control' %>
    </div>
</div>
<% end %>

app/views/sites/_site_card.html.erb
<% @sites.each do |site| %>
<div class="card">
    <%= image_tag site.image, class:"card-img-top", alt:"codego" %>
    <div class="card-block">
        <h4 class="card-title"><%= site.title %></h4>
        <p class="card-text"><%= site.description %></p>
        <div class="row">
            <div class="col-sm-6">
                <%= link_to site.link, class: "btn btn-block btn-outline-primary", target: "blank" do %>
                <i class="fa fa-fw fa-rocket mr-1"></i>Launch
                <% end %>
            </div>
            <div class="col-sm-6">
                <%= link_to site.github, class: "btn btn-block btn-outline-primary", target: "blank" do %>
                <i class="fa fa-fw fa-code mr-1"></i>Code
                <% end %>
            </div>
        </div>
        <% if user_signed_in? %>
        <div class="mt-3">
            <%= link_to 'Edit', edit_site_path(site) %>
        </div>
        <% end %>
    </div>
</div>
<% end %>

app/views/sites/edit.html.erb
<div id='pageContent' class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <h1>Editing Site</h1>
            <%= render 'form', site: @site %>
            <div class="row">
                <div class="col-md-12 text-center">
                    <%= link_to 'Show', @site %> |
                    <%= link_to 'Back', sites_path %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/sites/index.html.erb
<div id="pageContent" class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="float-sm-left">Sites</h1>
            <div class="float-sm-right">
                <%= link_to 'New Site', new_site_path, class: "btn btn-primary" %>
            </div>
            <table class="table table-hover">
                <thead class="thead-inverse">
                    <tr>
                        <th>Title</th>
                        <th>Image</th>
                        <th>Github</th>
                        <th>Link</th>
                        <th>Actions</th>
                    </tr>
                </thead>

                <tbody>
                    <% @sites.each do |site| %>
                    <tr>
                        <td><%= site.title %></td>
                        <td><%= link_to 'Image', site.image %></td>
                        <td><%= link_to 'Code', site.github %></td>
                        <td><%= link_to 'Site', site.link %></td>
                        <td>
                            <%= link_to site, title: "show" do %><span class="fa fa-eye mr-1"></span><% end %>
                            <%= link_to edit_site_path(site), title: "edit" do %><span class="fa fa-edit mr-1"></span><% end %>
                            <%= link_to site, method: :delete, data: { confirm: 'Are you sure?' }, title: "delete" do %><span class="fa fa-times"></span><% end %>
                        </td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/sites/new.html.erb
<div id='pageContent' class="col-md-4 offset-md-4">
<h1>New Site</h1>
<%= render 'form', site: @site %>
</div>

app/views/sites/show.html.erb
<div id="pageContent" class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <p>
              <strong>Title:</strong>
              <%= @site.title %>
            </p>

            <p>
              <strong>Image:</strong>
              <%= @site.image %>
            </p>

            <p>
              <strong>Github:</strong>
              <%= @site.github %>
            </p>

            <p>
              <strong>Link:</strong>
              <%= @site.link %>
            </p>

            <%= link_to 'Edit', edit_site_path(@site) %> |
            <%= link_to 'Back', sites_path %>
        </div>
    </div>
</div>